### ISSUE TITLE
Clarification on config (tessedit_char_whitelist)

### ISSUE THREAD

**Issue by ghartsho** [desmondmorris/node-tesseract#51]
I need to specify a character whitelist. The below code works, just wondering if this is the "proper" way to do it (config is joined together [here on L69 of lib/tesseract.js](https://github.com/desmondmorris/node-tesseract/blob/master/lib/tesseract.js#L69))

    var tesseract = require('node-tesseract');

    var image_path = 'captcha.gif';

    var options = {
        psm: 6,
        config: '-c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ23456789'
    };

    tesseract.process(image_path, options, function (err, txt) {
        if (err) console.error(err);
        else console.log(txt)
    });

**Comment by desmondmorris** [comment]
Hey @ghartsho!  Yah, that is the "proper" way to do it now.  Probably should allow that to take an object.  But for now, that is the way to go
